name: "Jesse B. Hannah"
handle: "jbhannah"

social:
  fb:
    name: "Facebook"
    url: "https://www.facebook.com/jbhannah"
  twitter:
    name: "Twitter"
    url: "https://twitter.com/jbhannah"
  linkedin:
    name: "LinkedIn"
    url: "https://www.linkedin.com/in/jbhannah"
  flickr:
    name: "Flickr"
    url: "http://www.flickr.com/photos/jbhannah"
  gh:
    name: "GitHub"
    url: "https://github.com/jbhannah"
  gplus:
    name: "Google+"
    url: "https://plus.google.com/115963221291991585027"
